pipeline {
    agent any
    
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/Manoj1904/Jenkins.git'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t manoj1904/devops:latest .'
            }
        }
        
        stage('Push to Docker Hub') {
            steps {
                sh 'docker login -u manoj1904 -p Manoj@19'
                sh 'docker push manoj1904/devops:latest'
            }
        }
        
        stage('Deploy') {
            steps {
                sh './deploy.sh'
            }
        }
    }
}
